### PR TITLE
Update Functions.swift

### PR DESCRIPTION
**Pull request by jaysonng**
Fix buildServerURL to not include default port 8081 when running in localhost or 127.0.0.1

### CODE REVIEW

**Comment by jaysonng** [comment]
Hi,

In ParseServerConfiguration the port 8081 is set as default and I didn't think touching all of that was way to go.

How do I " If there’s no port, you can make it not specify a default" ? as 8081 is set as the port by this point if there's no port set in ENV. 

What do you think is best way to achieve this?  I'll be happy to fix it to work better in a general sense.

**Comment by jaysonng** [comment]
Would love to hear your thoughts on this and maybe get it a fix in pulled.

**Comment by cbaker6** [comment]
You have merged changes from your other branches into here. All of those changes need to be removed

**Comment by cbaker6** [comment]
Closing this, feel free to open another PR if you have a different fix.

**Comment by jaysonng** [comment]
thanks for the fix!

**Pull request closed without merging**
